version: "3"

services:
  app-server:
    build: .
    volumes:
    - .:/app
    network_mode: host
    ports:
    - "3002:3002"
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
